//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanismanlikSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_DanismanlikEntities : DbContext
    {
        public DB_DanismanlikEntities()
            : base("name=DB_DanismanlikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_EkDosya> tbl_EkDosya { get; set; }
        public virtual DbSet<tbl_Kategori> tbl_Kategori { get; set; }
        public virtual DbSet<tbl_Kullanici> tbl_Kullanici { get; set; }
        public virtual DbSet<tbl_KullaniciRol> tbl_KullaniciRol { get; set; }
        public virtual DbSet<tbl_Proje> tbl_Proje { get; set; }
        public virtual DbSet<tbl_ProjeFoto> tbl_ProjeFoto { get; set; }
        public virtual DbSet<tbl_Yorum> tbl_Yorum { get; set; }
    }
}
