//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanismanlikSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Yorum
    {
        public int id_Yorum { get; set; }
        public Nullable<int> id_Kullanici { get; set; }
        public Nullable<int> id_Proje { get; set; }
        public string Yorum { get; set; }
        public Nullable<System.DateTime> YorumTarihi { get; set; }
        public Nullable<bool> OnaylandiMi { get; set; }
    
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
        public virtual tbl_Proje tbl_Proje { get; set; }
    }
}
